#!/bin/sh
set -eux

cat tests/test_input.txt | cargo run --example stdin | diff -u tests/test_output.txt -
cargo run --example stdin </dev/null | tail -n +2 | diff -u /dev/null -

cat tests/test_input.txt | cargo run --example stdin_stream | diff -u tests/test_stream_output.txt -
cargo run --example stdin_stream </dev/null | tail -n +2 | diff -u /dev/null -

cat tests/test_input.txt | cargo run --example stdin_lines | diff -u tests/test_lines_output.txt -
cargo run --example stdin_lines </dev/null | tail -n +2 | diff -u /dev/null -
