#!/usr/bin/env bash
set -eux
{
    sleep 0.01
    cat tests/test_input.txt
} | cargo run --example stdin | diff -u tests/test_output.txt -
cargo run --example stdin </dev/null | tail -n +2 | diff -u /dev/null -

cargo run --example seek
diff -q tests/seek.txt <(echo aaccccAAbbbbbbbb)
